hashtag_anime = [
    "#animediffusions #animegirls #animeart #manga #animeartstyle #otaku #animedrawing #fanart #animefanart #animefan #animegirl #kawaii",
    "#animediffusions #animebeauty #animegirlsofinstagram #animeaesthetic #animegirlmodel #animecharacter #animegirlsportrait #animegirlportrait #animestyle #animecharacterdesign #animecute",
    "#animediffusions #animegirlscosplay #animegirlsfashion #animegirlsdaily #animegirlstyle #animegirloutfit #animegirlmodel #animegirlmakeup #animegirlswithglasses #animegirlsglasses #animegirlslove"
]

hashtag_ai = "#stableDiffusion #generatedArt #artificialIntelligence #AIart #machineLearning #deepLearning #neuralNetworks #digitalArt #generatedGraphics #computationalArt #waifuanime #animeai"

names = [
    {"romaji": "Akane", "kanji": "茜"},
    {"romaji": "Aiko", "kanji": "愛子"},
    {"romaji": "Ami", "kanji": "亜美"},
    {"romaji": "Asuka", "kanji": "飛鳥"},
    {"romaji": "Ayaka", "kanji": "彩花"},
    {"romaji": "Chie", "kanji": "千恵"},
    {"romaji": "Emi", "kanji": "恵美"},
    {"romaji": "Eri", "kanji": "絵梨"},
    {"romaji": "Haruka", "kanji": "遥"},
    {"romaji": "Hikari", "kanji": "光"},
    {"romaji": "Hina", "kanji": "陽菜"},
    {"romaji": "Honoka", "kanji": "帆乃花"},
    {"romaji": "Kana", "kanji": "佳奈"},
    {"romaji": "Kanako", "kanji": "加奈子"},
    {"romaji": "Kaori", "kanji": "香"},
    {"romaji": "Kasumi", "kanji": "かすみ"},
    {"romaji": "Kokoro", "kanji": "心"},
    {"romaji": "Kumi", "kanji": "久美"},
    {"romaji": "Mai", "kanji": "舞"},
    {"romaji": "Maki", "kanji": "真希"},
    {"romaji": "Mana", "kanji": "愛"},
    {"romaji": "Mao", "kanji": "真央"},
    {"romaji": "Mari", "kanji": "麻里"},
    {"romaji": "Mayu", "kanji": "真由"},
    {"romaji": "Miharu", "kanji": "美春"},
    {"romaji": "Mika", "kanji": "美香"},
    {"romaji": "Miku", "kanji": "美久"},
    {"romaji": "Misaki", "kanji": "美咲"},
    {"romaji": "Miyu", "kanji": "美優"},
    {"romaji": "Nana", "kanji": "菜々"},
    {"romaji": "Nanami", "kanji": "七海"},
    {"romaji": "Natsumi", "kanji": "夏美"},
    {"romaji": "Nozomi", "kanji": "希"},
    {"romaji": "Reina", "kanji": "玲奈"},
    {"romaji": "Rina", "kanji": "莉奈"},
    {"romaji": "Rio", "kanji": "莉桜"},
    {"romaji": "Risa", "kanji": "理沙"},
    {"romaji": "Rui", "kanji": "瑠衣"},
    {"romaji": "Runa", "kanji": "留菜"},
    {"romaji": "Sakura", "kanji": "桜"},
    {"romaji": "Sana", "kanji": "早菜"},
    {"romaji": "Sayaka", "kanji": "沙也香"},
    {"romaji": "Sayuri", "kanji": "小百合"},
    {"romaji": "Shiori", "kanji": "詩織"},
    {"romaji": "Sora", "kanji": "空"},
    {"romaji": "Sumire", "kanji": "菫"},
    {"romaji": "Tsubasa", "kanji": "翼"},
    {"romaji": "Yua", "kanji": "優愛"},
    {"romaji": "Yui", "kanji": "結衣"},
    {"romaji": "Yuka", "kanji": "優香"},
    {"romaji": "Yuki", "kanji": "雪"},
    {"romaji": "Yukiko", "kanji": "幸子"},
    {"romaji": "Yuna", "kanji": "優奈"},
    {"romaji": "Yuri", "kanji": "百合"},
    {"romaji": "Yuriko", "kanji": "百子"}
]
surnames = [
    {"romaji": "Sato", "kanji": "佐藤"},
    {"romaji": "Suzuki", "kanji": "鈴木"},
    {"romaji": "Takahashi", "kanji": "高橋"},
    {"romaji": "Tanaka", "kanji": "田中"},
    {"romaji": "Watanabe", "kanji": "渡辺"},
    {"romaji": "Ito", "kanji": "伊藤"},
    {"romaji": "Yamamoto", "kanji": "山本"},
    {"romaji": "Nakamura", "kanji": "中村"},
    {"romaji": "Kobayashi", "kanji": "小林"},
    {"romaji": "Saito", "kanji": "斎藤"},
    {"romaji": "Kato", "kanji": "加藤"},
    {"romaji": "Yoshida", "kanji": "吉田"},
    {"romaji": "Yamada", "kanji": "山田"},
    {"romaji": "Sasaki", "kanji": "佐々木"},
    {"romaji": "Yamaguchi", "kanji": "山口"},
    {"romaji": "Matsumoto", "kanji": "松本"},
    {"romaji": "Inoue", "kanji": "井上"},
    {"romaji": "Kimura", "kanji": "木村"},
    {"romaji": "Hayashi", "kanji": "林"},
    {"romaji": "Shimizu", "kanji": "清水"},
    {"romaji": "Mori", "kanji": "森"},
    {"romaji": "Abe", "kanji": "阿部"},
    {"romaji": "Ikeda", "kanji": "池田"},
    {"romaji": "Hashimoto", "kanji": "橋本"},
    {"romaji": "Ishikawa", "kanji": "石川"},
    {"romaji": "Nakajima", "kanji": "中島"},
    {"romaji": "Matsuda", "kanji": "松田"},
    {"romaji": "Fujita", "kanji": "藤田"},
    {"romaji": "Okada", "kanji": "岡田"},
    {"romaji": "Ogawa", "kanji": "小川"},
    {"romaji": "Hasegawa", "kanji": "長谷川"},
    {"romaji": "Murakami", "kanji": "村上"},
    {"romaji": "Kondo", "kanji": "近藤"},
    {"romaji": "Ishii", "kanji": "石井"},
    {"romaji": "Yamashita", "kanji": "山下"},
    {"romaji": "Morita", "kanji": "森田"},
    {"romaji": "Ota", "kanji": "太田"},
    {"romaji": "Miura", "kanji": "三浦"},
    {"romaji": "Ueda", "kanji": "上田"},
    {"romaji": "Sugiyama", "kanji": "杉山"},
    {"romaji": "Takagi", "kanji": "高木"},
    {"romaji": "Sakamoto", "kanji": "坂本"}
]
